# Generated by Django 4.2.13 on 2025-05-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewexperience',
            name='interview_question',
            field=models.TextField(blank=True),
        ),
    ]
