# Generated by Django 4.2.13 on 2025-05-06 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_app', '0003_alter_interviewexperience_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewexperience',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interviewexperience',
            name='interview_question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='interviewexperience',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
